services:
  - type: web
    name: my-fastapi-app # Or whatever your service name is
    env: python
    runtime: python3.13.0 # Make sure this matches your desired Python version
    rootDir: fastapi_backend # Add this if your code is in a subdirectory
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "alembic upgrade head" # <--- MIGRATION COMMAND HERE
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT" # Adjust if your start command is different
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_database # Replace with your Render Database name
          property: connectionString
      # Add any other environment variables needed
